["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
aave_oracle = [
    "./contracts/misc/aave_oracle.cairo",
]
a_token = [
    "contracts/protocol/tokenization/a_token.cairo",
]
pool = [
    "./contracts/protocol/pool/pool.cairo",
]
pool_addresses_provider = [
    "./contracts/protocol/configuration/pool_addresses_provider.cairo",
]
pool_configurator = [
    "./contracts/protocol/pool/pool_configurator.cairo",
]
stable_debt_token = [
    "./contracts/protocol/tokenization/stable_debt_token.cairo",
]
variable_debt_token = [
    "./contracts/protocol/tokenization/variable_debt_token.cairo",
]
price_oracle_sentinel = [
    "./contracts/protocol/configuration/price_oracle_sentinel.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]

[profile.devnet.protostar.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"