["protostar.config"]
protostar_version = "0.2.3"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
a_token = [
    "contracts/protocol/tokenization/a_token.cairo",
]
pool = [
    "./contracts/protocol/pool/pool.cairo",
]
pool_addresses_provider = [
    "./contracts/protocol/configuration/pool_addresses_provider.cairo",
]
aave_oracle = [
    "./contracts/misc/aave_oracle.cairo",
]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
stdout-on-success = true

[profile.devnet.protostar.deploy]
gateway-url = "http://127.0.0.1:5050/"

[profile.testnet.protostar.deploy]
network="alpha-goerli"