name: Check format and build contracts

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  PROTOSTAR_VERSION: "0.4.2"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Install Protostar
        shell: bash
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash  -s -- -v $PROTOSTAR_VERSION

      - name: Install submodules
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar install

      - name: Install cairo-toolkit
        run: |
          pip install cairo-toolkit

      - name: Check format
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar format contracts --check && protostar format tests --check

      - name: Check interfaces
        run: |
          cairo-toolkit check-interface --protostar -d contracts/interfaces

      - name: Build contracts
        run: |
          export PATH="$PATH:/home/runner/.protostar/dist/protostar" && protostar build
