name: Generate documentation

on:
  push:
    branches:
      - main

env:
  PROTOSTAR_VERSION: "0.4.2"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install mdutils pyyaml
      - name: Install kaaper
        run: |
          git clone https://github.com/msaug/kaaper && cd kaaper/cli && npm i && npm run build && npm i -g . && cd ../../
      - name: Generate yaml documentation
        run: |
          kaaper generate ./contracts ./docs/data/contracts --standard natspec && rm -rf kaaper
      - name: Generate markdown files
        run: |
          python3 docs/build.py
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.15.4
        with:
          commit_message: Generate documentation
          create_branch: false
      - name: Push changes
        run: |
          git push
